# Generated by Django 2.2 on 2020-05-13 15:19

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reunion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cedula', models.CharField(max_length=10)),
                ('nombre', models.CharField(max_length=45)),
                ('razon_social', models.CharField(max_length=45, null=True)),
                ('correo', models.EmailField(max_length=254)),
                ('piso', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4')], max_length=1)),
                ('horario', models.DateTimeField()),
                ('activa', models.BooleanField(default=True)),
                ('descripcion', models.TextField(max_length=100)),
                ('create_at', models.DateTimeField(default=datetime.datetime(2020, 5, 13, 10, 19, 15, 97720), editable=False)),
                ('edited_at', models.DateTimeField(editable=False)),
            ],
        ),
        migrations.CreateModel(
            name='Historial',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ingreso', models.BooleanField(default=True)),
                ('create_at', models.DateTimeField(default=datetime.datetime(2020, 5, 13, 10, 19, 15, 98244), editable=False)),
                ('reunion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ingreso_proveedores.Reunion')),
            ],
        ),
    ]
