# Generated by Django 2.2 on 2020-05-13 15:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingreso_proveedores', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historial',
            name='create_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 13, 10, 20, 4, 45714), editable=False),
        ),
        migrations.AlterField(
            model_name='reunion',
            name='create_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 13, 10, 20, 4, 45714), editable=False),
        ),
    ]
