# Generated by Django 2.2 on 2020-05-13 19:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingreso_proveedores', '0002_auto_20200513_1020'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historial',
            options={'verbose_name_plural': 'Historial'},
        ),
        migrations.AlterModelOptions(
            name='reunion',
            options={'verbose_name_plural': 'Reuniones'},
        ),
        migrations.AddField(
            model_name='reunion',
            name='cantidad_personas',
            field=models.IntegerField(default=1, max_length=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='historial',
            name='create_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 13, 14, 50, 0, 437451), editable=False),
        ),
        migrations.AlterField(
            model_name='reunion',
            name='create_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 13, 14, 50, 0, 437451), editable=False),
        ),
    ]
