# Generated by Django 2.2 on 2020-05-15 23:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingreso_proveedores', '0006_auto_20200515_1652'),
    ]

    operations = [
        migrations.AddField(
            model_name='historial',
            name='detalle',
            field=models.TextField(default=1, max_length=300),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='historial',
            name='create_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 15, 18, 40, 19, 639669), editable=False),
        ),
        migrations.AlterField(
            model_name='reunion',
            name='create_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 15, 18, 40, 19, 639669), editable=False),
        ),
        migrations.AlterField(
            model_name='sala',
            name='create_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 15, 18, 40, 19, 638663), editable=False),
        ),
    ]
