# Generated by Django 2.2 on 2020-05-20 16:37

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ingreso_proveedores', '0007_auto_20200515_1840'),
    ]

    operations = [
        migrations.AddField(
            model_name='reunion',
            name='autor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='historial',
            name='create_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 20, 11, 37, 9, 423988), editable=False),
        ),
        migrations.AlterField(
            model_name='reunion',
            name='create_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 20, 11, 37, 9, 423988), editable=False),
        ),
        migrations.AlterField(
            model_name='sala',
            name='create_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 20, 11, 37, 9, 423988), editable=False),
        ),
    ]
