# Generated by Django 2.2 on 2020-05-22 20:47

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ingreso_proveedores', '0009_auto_20200522_1439'),
    ]

    operations = [
        migrations.AddField(
            model_name='historial',
            name='autor',
            field=models.ForeignKey(default=1, editable=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='historial',
            name='create_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 22, 15, 47, 28, 550558), editable=False),
        ),
        migrations.AlterField(
            model_name='reunion',
            name='create_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 22, 15, 47, 28, 549555), editable=False),
        ),
        migrations.AlterField(
            model_name='sala',
            name='create_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 22, 15, 47, 28, 549555), editable=False),
        ),
    ]
