# Generated by Django 2.2 on 2020-05-22 20:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingreso_proveedores', '0010_auto_20200522_1547'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historial',
            name='create_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 22, 15, 48, 34, 85371), editable=False),
        ),
        migrations.AlterField(
            model_name='reunion',
            name='cedula',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='reunion',
            name='create_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 22, 15, 48, 34, 84368), editable=False),
        ),
        migrations.AlterField(
            model_name='sala',
            name='create_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 22, 15, 48, 34, 84368), editable=False),
        ),
    ]
