# Generated by Django 2.2 on 2020-05-03 19:52

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Colaborador',
            fields=[
                ('cedula', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=45)),
                ('correo', models.EmailField(max_length=254)),
                ('activo', models.BooleanField(default=False)),
                ('correo_jefe', models.EmailField(max_length=254)),
                ('piso', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4')], max_length=1)),
                ('saludable', models.BooleanField(default=False, editable=False)),
                ('fecha', models.DateTimeField(default=datetime.datetime(2020, 5, 3, 14, 52, 43, 195671), editable=False)),
            ],
        ),
        migrations.CreateModel(
            name='Horario',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=45)),
                ('lunes_entrada', models.TimeField(blank=True, null=True)),
                ('lunes_salida', models.TimeField(blank=True, null=True)),
                ('martes_entrada', models.TimeField(blank=True, null=True)),
                ('martes_salida', models.TimeField(blank=True, null=True)),
                ('miercoles_entrada', models.TimeField(blank=True, null=True)),
                ('miercoles_salida', models.TimeField(blank=True, null=True)),
                ('jueves_entrada', models.TimeField(blank=True, null=True)),
                ('jueves_salida', models.TimeField(blank=True, null=True)),
                ('viernes_entrada', models.TimeField(blank=True, null=True)),
                ('viernes_salida', models.TimeField(blank=True, null=True)),
                ('sabado_entrada', models.TimeField(blank=True, null=True)),
                ('sabado_salida', models.TimeField(blank=True, null=True)),
                ('domingo_entrada', models.TimeField(blank=True, null=True)),
                ('domingo_salida', models.TimeField(blank=True, null=True)),
                ('fecha', models.DateTimeField(default=datetime.datetime(2020, 5, 3, 14, 52, 43, 194670), editable=False)),
            ],
        ),
        migrations.CreateModel(
            name='Ingreso',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateTimeField(default=datetime.datetime(2020, 5, 3, 14, 52, 43, 196674))),
                ('temperatura', models.FloatField()),
                ('permitido', models.BooleanField()),
                ('observacion', models.CharField(max_length=100)),
                ('accion', models.CharField(choices=[('in', 'in'), ('out', 'out')], max_length=3)),
                ('nombre', models.CharField(editable=False, max_length=45)),
                ('cedula', models.CharField(editable=False, max_length=10)),
                ('colaborador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ingreso_oficina.Colaborador')),
            ],
        ),
        migrations.CreateModel(
            name='Evaluacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observacion', models.TextField()),
                ('saludable', models.BooleanField()),
                ('nombre', models.CharField(editable=False, max_length=45)),
                ('cedula', models.CharField(editable=False, max_length=45)),
                ('fecha', models.DateTimeField(default=datetime.datetime(2020, 5, 3, 14, 52, 43, 195671), editable=False)),
                ('colaborador', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='ingreso_oficina.Colaborador')),
            ],
        ),
        migrations.AddField(
            model_name='colaborador',
            name='horario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ingreso_oficina.Horario'),
        ),
    ]
