# Generated by Django 2.2 on 2020-05-03 19:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingreso_oficina', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colaborador',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 3, 14, 52, 48, 852371), editable=False),
        ),
        migrations.AlterField(
            model_name='evaluacion',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 3, 14, 52, 48, 852873), editable=False),
        ),
        migrations.AlterField(
            model_name='horario',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 3, 14, 52, 48, 851869), editable=False),
        ),
        migrations.AlterField(
            model_name='ingreso',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 3, 14, 52, 48, 853374)),
        ),
    ]
