# Generated by Django 2.2 on 2020-05-03 19:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingreso_oficina', '0002_auto_20200503_1452'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colaborador',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 3, 14, 52, 55, 279951), editable=False),
        ),
        migrations.AlterField(
            model_name='evaluacion',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 3, 14, 52, 55, 280960), editable=False),
        ),
        migrations.AlterField(
            model_name='horario',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 3, 14, 52, 55, 279951), editable=False),
        ),
        migrations.AlterField(
            model_name='ingreso',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 3, 14, 52, 55, 280960)),
        ),
    ]
